name: CI/CD Pipeline
on:
  push:
    branches:
      - main
env:
  IMAGE: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USERNAME }}/${{ github.event.repository.name }}:latest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: 
            BASE_URL=${{ vars.BASE_URL }}
          tags: ${{ env.IMAGE }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to the host with SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo podman login ${{ vars.REGISTRY }} -u ${{ vars.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
            sudo podman pull ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USERNAME }}/${{ github.event.repository.name }}:latest
            sudo podman run -d -p ${{ vars.PUBLISH_PORT }}:8000 -v /etc/localtime:/etc/localtime:ro --restart always --replace --name ${{ github.event.repository.name }} ${{ env.IMAGE }}
